export const site = {
  name: 'Local Foundary',
  url: 'https://www.localfoundary.co.uk',
  email: 'info@localfoundary.co.uk',
  phoneDisplay: '07518 853582',
  phone: '+447518853582',
  whatsapp: 'https://api.whatsapp.com/send?phone=447518853582&text=Hi%20Local%20Foundary%2C%20I%27d%20like%20to%20discuss%20a%20project.',
  location: 'United Kingdom',
  area: 'UK and international businesses',
};

export const capabilities = [
  {
    key: 'strategy',
    number: '01',
    label: 'Strategy',
    title: 'Turn competing ideas into a clear digital plan.',
    copy: 'Positioning, customer journeys and commercial priorities that give every channel a defined job to do.',
    deliverables: ['Digital audit', 'Positioning', 'Customer journeys', 'Growth priorities'],
    href: '/services/digital-strategy/',
  },
  {
    key: 'build',
    number: '02',
    label: 'Websites',
    title: 'Websites designed to earn the next step.',
    copy: 'Bespoke, responsive websites shaped around your company, your customers and the action that matters most.',
    deliverables: ['UX strategy', 'Web design', 'Development', 'Integrations'],
    href: '/services/website-design/',
  },
  {
    key: 'commerce',
    number: '03',
    label: 'E-commerce',
    title: 'Turn product interest into confident purchases.',
    copy: 'Clear product discovery, strong presentation and low-friction buying journeys across desktop and mobile.',
    deliverables: ['Shop strategy', 'Product UX', 'Checkout journeys', 'Store integrations'],
    href: '/services/ecommerce/',
  },
  {
    key: 'found',
    number: '04',
    label: 'Search',
    title: 'Build visibility where demand already exists.',
    copy: 'Technical SEO, content structure and local or national visibility aligned to the way customers search for what you offer. Page intent, content gaps and measurement are prioritised around a clear commercial purpose.',
    deliverables: ['Technical SEO', 'Content structure', 'Local visibility', 'Measurement'],
    href: '/services/local-seo/',
  },
  {
    key: 'leads',
    number: '05',
    label: 'Conversion',
    title: 'Landing pages built for qualified enquiries.',
    copy: 'Landing pages, forms, booking systems and enquiry paths designed around the right next step for the customer.',
    deliverables: ['Landing pages', 'Lead capture', 'Booking systems', 'Conversion paths'],
    href: '/services/landing-pages-lead-generation/',
  },
  {
    key: 'support',
    number: '06',
    label: 'Support',
    title: 'Keep the website supported after launch.',
    copy: 'Hosting, maintenance and updates handled through a clear scope, with no surprises about responsibilities or ongoing costs.',
    deliverables: ['Hosting setup', 'Maintenance scope', 'Technical checks', 'Update options'],
    href: '/services/hosting-support/',
  },
];

export const projects = [
  {
    slug: 'iffy-khan',
    name: 'Iffy Khan',
    industry: 'Dubai & Abu Dhabi property',
    type: 'Premium personal brand',
    summary: 'A cinematic personal-brand website designed to communicate property expertise across Dubai and Abu Dhabi, with clear routes into conversation.',
    headline: 'A premium digital presence for Dubai property specialist Iffy Khan.',
    services: ['Brand positioning', 'Website design', 'Responsive development', 'Scroll direction', 'WhatsApp journeys'],
    challenge: 'Bring property expertise and a personal brand together in an experience that feels credible at the premium end of the market.',
    strategy: 'Use direct investment messaging, confident editorial pacing and purposeful enquiry routes to make a complex offer easier to navigate.',
    features: ['Personal-brand storytelling', 'Dubai and Abu Dhabi area content', 'Cinematic visual direction', 'Mobile-first WhatsApp contact'],
    outcome: null,
    liveUrl: 'https://iffykhan.ae/',
    visual: 'screenshot',
    desktopImage: '/assets/work/iffy-khan/site-desktop.jpg',
    mobileImage: '/assets/work/iffy-khan/site-mobile.jpg',
    desktopWidth: 1425,
    desktopHeight: 972,
    mobileWidth: 375,
    mobileHeight: 812,
    featured: true,
    published: true,
    assetStatus: null,
    seoTitle: 'Iffy Khan Property Website Case Study | Local Foundary',
    seoDescription: 'A property and personal-brand website for Dubai and Abu Dhabi specialist Iffy Khan, designed around credibility, expertise and direct enquiries.',
  },
  {
    slug: 'ste-hamilton-fitness',
    name: 'Ste Hamilton Fitness',
    industry: 'Fitness & coaching',
    type: 'Personal-brand website',
    summary: 'A high-energy fitness website built around coaching, client transformations and personality, with direct routes into an enquiry.',
    headline: 'Turning coaching results into a stronger personal brand.',
    services: ['Website design', 'Responsive development', 'Content hierarchy', 'Lead generation', 'WhatsApp journey'],
    challenge: 'Present coaching services, personality and transformation content in one focused experience without losing pace on mobile.',
    strategy: 'Lead with the coach, make service choices easy to compare and keep the route to contact present throughout the journey.',
    features: ['Coaching information', 'Transformation galleries', 'Photography-led design', 'Direct WhatsApp enquiry'],
    outcome: null,
    liveUrl: 'https://www.stehamiltonfitness.com/',
    visual: 'screenshot',
    desktopImage: '/assets/work/ste-hamilton-fitness/site-desktop.jpg',
    mobileImage: '/assets/work/ste-hamilton-fitness/site-mobile.jpg',
    desktopWidth: 1425,
    desktopHeight: 972,
    mobileWidth: 375,
    mobileHeight: 812,
    featured: true,
    published: true,
    assetStatus: null,
    seoTitle: 'Ste Hamilton Fitness Website Case Study | Local Foundary',
    seoDescription: 'A high-energy fitness website for Ste Hamilton Fitness, combining coaching services, transformation stories, personality and clear enquiry journeys.',
  },
  {
    slug: 'pat-barrett',
    name: 'Pat Barrett',
    industry: 'Boxing, entertainment & events',
    type: 'Performer and personal brand',
    summary: 'A personality-led home for former British and European champion “Black Flash” Pat Barrett, bringing story, media, events and ticketing together.',
    headline: 'A digital home for “Black Flash” Pat Barrett.',
    services: ['Website design', 'Responsive development', 'Media presentation', 'Event promotion', 'Ticket Tailor integration'],
    challenge: 'Give a storied boxing career a modern home while making current appearances, media and ticket journeys easy to find.',
    strategy: 'Balance archive-led storytelling with clear present-day actions, using a bold visual system grounded in Pat’s identity and career.',
    features: ['Career storytelling', 'Professional record', 'Media gallery', 'Event listings', 'Ticket Tailor integration'],
    outcome: null,
    liveUrl: 'https://www.patbarrett.co.uk/',
    visual: 'screenshot',
    desktopImage: '/assets/work/pat-barrett/site-desktop.jpg',
    mobileImage: '/assets/work/pat-barrett/site-mobile.jpg',
    desktopWidth: 1425,
    desktopHeight: 990,
    mobileWidth: 375,
    mobileHeight: 812,
    featured: true,
    published: true,
    assetStatus: null,
    seoTitle: 'Pat Barrett Website Case Study | Local Foundary',
    seoDescription: 'A boxing and events website for former British and European champion Pat Barrett, bringing his career, media, appearances and ticketing together.',
  },
];

export const processSteps = [
  { number: '01', name: 'Discover', copy: 'We learn about the business, market, customer, current digital presence and the commercial objective behind the project.', deliverable: 'Discovery brief and priorities', required: 'Access to current assets, business information and the people who understand the customer.', feedback: 'A focused discovery conversation and confirmation that the brief is accurate.' },
  { number: '02', name: 'Strategise', copy: 'We define the positioning, content hierarchy, user journey, website structure and the actions that will measure success.', deliverable: 'Strategy, sitemap and delivery plan', required: 'Agreement on priorities, audience and any technical or operational constraints.', feedback: 'A structured review before design begins, so important decisions are made early.' },
  { number: '03', name: 'Design & Build', copy: 'We create the copy, interface and responsive website experience, then connect the forms, commerce or booking tools the project needs.', deliverable: 'Approved design and working website', required: 'Timely access to content, photography, product information and integration accounts.', feedback: 'Defined review rounds at the design and working-site stages, with consolidated comments.' },
  { number: '04', name: 'Launch & Grow', copy: 'We complete content, search, accessibility and device checks before launch, then support and improve the site as the business develops.', deliverable: 'Quality-assured launch and support plan', required: 'Final approval, domain access and a named person for launch decisions.', feedback: 'A controlled sign-off, followed by agreed support, measurement and optimisation.' },
];

export const industries = [
  { slug: 'professional-services', name: 'Professional Services', short: 'Authority-led experiences for solicitors, accountants, advisers and specialist firms.', code: 'PRO', need: 'Clear expertise, service pathways and evidence of professional credibility.', trust: 'People, credentials, insight and relevant experience.', action: 'Book a consultation or make a qualified enquiry.', systems: 'CRM, consultation booking and document capture.', links: [{ name: 'Website design', href: '/services/website-design/' }, { name: 'Website copywriting', href: '/services/copy-content/' }] },
  { slug: 'ecommerce-retail', name: 'E-commerce & Retail', short: 'Product-led journeys that make discovery, comparison and purchase feel effortless.', code: 'COM', need: 'Strong product presentation, navigation and frictionless buying.', trust: 'Reviews, delivery clarity, returns and secure checkout.', action: 'Purchase, subscribe or join a product launch.', systems: 'Shop platform, payments, email and inventory.', links: [{ name: 'E-commerce design', href: '/services/ecommerce/' }, { name: 'Website copywriting', href: '/services/copy-content/' }] },
  { slug: 'healthcare-clinics', name: 'Healthcare & Clinics', short: 'Calm, accessible experiences that balance expertise, reassurance and easy booking.', code: 'HLT', need: 'Accessible information, treatment clarity and a reassuring patient journey.', trust: 'Practitioner profiles, qualifications and responsible proof.', action: 'Book, call or request an initial consultation.', systems: 'Booking, patient enquiries and compliant integrations.', links: [{ name: 'Website design', href: '/services/website-design/' }, { name: 'Search visibility', href: '/services/local-seo/' }] },
  { slug: 'property-real-estate', name: 'Property & Real Estate', short: 'High-quality presentation for agencies, developments, advisers and property specialists.', code: 'PRP', need: 'Confident visual presentation and clear routes through services or listings.', trust: 'Market knowledge, instructions, track record and people.', action: 'Request a valuation, register interest or enquire.', systems: 'Property feeds, CRM, valuation and appointment tools.', links: [{ name: 'Iffy Khan case study', href: '/work/iffy-khan/' }, { name: 'Website design', href: '/services/website-design/' }] },
  { slug: 'hospitality-venues', name: 'Hospitality & Venues', short: 'Atmosphere-led digital experiences that turn browsing into bookings and visits.', code: 'HSP', need: 'A strong sense of place, practical information and mobile-first booking.', trust: 'Menus, imagery, reviews and clear policies.', action: 'Reserve, book an event or buy a ticket.', systems: 'Reservations, ticketing, menus and gift cards.', links: [{ name: 'Landing pages', href: '/services/landing-pages-lead-generation/' }, { name: 'E-commerce', href: '/services/ecommerce/' }] },
  { slug: 'construction-trades', name: 'Construction & Trades', short: 'Project and service websites that make quality, coverage and the right route to enquire clear.', code: 'CON', need: 'Clear services, areas, accreditations and proof of completed work.', trust: 'Projects, qualifications, reviews and response expectations.', action: 'Request a quote, call or submit project details.', systems: 'Quote forms, call journeys and local search.', links: [{ name: 'Website design', href: '/services/website-design/' }, { name: 'Local SEO', href: '/services/local-seo/' }], campaignLinks: [{ name: 'Websites for plumbers', href: '/websites-for-plumbers/' }, { name: 'Websites for electricians', href: '/websites-for-electricians/' }, { name: 'Websites for builders', href: '/websites-for-builders/' }, { name: 'Websites for service businesses', href: '/websites-for-service-businesses/' }] },
  { slug: 'fitness-wellness', name: 'Fitness & Wellness', short: 'Personality-led websites for coaches, gyms, studios and wellbeing businesses.', code: 'FIT', need: 'A clear offer, motivating proof and an easy path into the right service.', trust: 'Expertise, approach, transformations and community.', action: 'Join, book a session or start a conversation.', systems: 'Class booking, memberships and lead capture.', links: [{ name: 'Ste Hamilton case study', href: '/work/ste-hamilton-fitness/' }, { name: 'Lead generation', href: '/services/landing-pages-lead-generation/' }] },
  { slug: 'beauty-lifestyle', name: 'Beauty & Lifestyle', short: 'Polished, mobile-first experiences that make services and brand value tangible.', code: 'BTY', need: 'Strong visual identity, treatment clarity and simple mobile navigation.', trust: 'Portfolio work, practitioner expertise and reviews.', action: 'Book, buy or enquire about a service.', systems: 'Appointment booking, deposits and product sales.', links: [{ name: 'Brand identity', href: '/services/branding/' }, { name: 'Website design', href: '/services/website-design/' }] },
  { slug: 'consultants-coaches', name: 'Consultants & Coaches', short: 'Thoughtful personal-brand platforms that turn expertise into a clear commercial offer.', code: 'CCH', need: 'Distinct positioning, packaged services and visible expertise.', trust: 'Ideas, client fit, approach and relevant proof.', action: 'Send an enquiry, download a resource or apply to work together.', systems: 'Email journeys, application forms and enquiry management.', links: [{ name: 'Brand identity', href: '/services/branding/' }, { name: 'Website copywriting', href: '/services/copy-content/' }] },
  { slug: 'automotive', name: 'Automotive', short: 'Trust-rich websites for specialists, dealers, workshops and premium vehicle services.', code: 'AUT', need: 'Service clarity, strong visual proof and fast mobile contact.', trust: 'Facilities, accreditations, stock and customer evidence.', action: 'Book, value a vehicle or request a quote.', systems: 'Stock feeds, booking and finance enquiries.', links: [{ name: 'Website design', href: '/services/website-design/' }, { name: 'Lead generation', href: '/services/landing-pages-lead-generation/' }] },
  { slug: 'education-training', name: 'Education & Training', short: 'Structured experiences that help learners understand value, outcomes and next steps.', code: 'EDU', need: 'Clear programmes, audiences, schedules and learning outcomes.', trust: 'Tutors, accreditation, curriculum and learner evidence.', action: 'Apply, enrol, book or request information.', systems: 'Learning platforms, enrolment and payment.', links: [{ name: 'Website copywriting', href: '/services/copy-content/' }, { name: 'Website design', href: '/services/website-design/' }] },
  { slug: 'startups-technology', name: 'Start-ups & Technology', short: 'Focused digital platforms that explain new ideas quickly and scale with the company.', code: 'TEC', need: 'Sharp positioning, product clarity and a flexible growth foundation.', trust: 'Team, product evidence, security and customer fit.', action: 'Request a demo, join a waitlist or start a trial.', systems: 'Product demos, CRM, onboarding and analytics.', links: [{ name: 'Digital strategy', href: '/services/digital-strategy/' }, { name: 'Website design', href: '/services/website-design/' }] },
];

export const pricing = [
  {
    name: 'Launch',
    kicker: 'Focused website',
    price: '£549',
    description: 'A focused, professional starting point for a business that needs a clear and credible online presence.',
    features: ['Up to 5 pages', 'Responsive custom design', 'Enquiry form and contact links', 'Standard hosting setup', 'On-page SEO foundations', 'Two years of standard hosting and one eligible domain registration'],
  },
  {
    name: 'Growth',
    kicker: 'Website & visibility',
    price: '£949',
    description: 'A broader digital foundation for businesses ready to connect website, search visibility and customer trust.',
    features: ['Everything in Launch', 'Up to 10 pages', 'Google Business Profile setup', 'Local SEO foundations', 'Structured data', 'Review integration', 'Two years of standard hosting and one eligible domain registration'],
    featured: true,
  },
  {
    name: 'Scale',
    kicker: 'Growth platform',
    price: null,
    priceLabel: 'Tailored quote',
    priceNote: 'Tailored to the agreed scope',
    description: 'A tailored platform for a broader offer or more complex customer journey, including e-commerce, branding or digital strategy where the agreed scope requires it.',
    features: ['Everything in Growth', 'Strategy and positioning workshop', 'Expanded page scope agreed in proposal', 'Brand refinement or e-commerce scope where required', 'Lead capture automation', 'Advanced SEO and content structure', 'Analytics setup and a post-launch performance review', 'Priority support during the agreed launch period', 'Two years of standard hosting and one eligible domain registration'],
  },
];

export const homeFaqs = [
  ['What kind of businesses can you support?', 'Our approach can be adapted to professional services, e-commerce, healthcare, property, hospitality, construction, fitness, lifestyle and many other sectors. Explore the industries page for the customer journeys and trust signals we consider.'],
  ['Do you only build websites?', 'No. Local Foundary can bring digital strategy, positioning, website or e-commerce design, search visibility, copy, conversion systems and ongoing care into one joined-up online presence.'],
  ['How quickly can a project launch?', 'A focused site can move quickly, but timing depends on scope, content and feedback. We agree a realistic schedule before work begins rather than promising an instant launch.'],
  ['Can you improve an existing site?', 'Yes. We can assess what is worth keeping, then recommend a focused redesign, technical improvement or a new build.'],
  ['What happens after launch?', 'Every project includes an agreed support period. Hosting, renewal and minor content updates can then continue through the annual renewal or monthly care-plan options described on the pricing page.'],
  ['Will you guarantee Google rankings or enquiries?', 'No credible agency can guarantee rankings or a fixed number of enquiries. We build strong technical, content and conversion foundations, then improve them with evidence.'],
];

export const servicePages = [
  {
    slug: 'digital-strategy',
    name: 'Digital strategy',
    eyebrow: 'Digital strategy',
    title: 'Digital strategy that gives every decision a clearer direction.',
    intro: 'We connect your commercial goals, customer behaviour and current digital activity to define what to improve first — and what can wait.',
    deliverables: ['Digital presence audit', 'Customer and competitor review', 'Positioning priorities', 'Customer journey mapping', 'Channel and content priorities', 'Measurement plan', 'Practical roadmap'],
    relatedProject: 'iffy-khan',
    seoTitle: 'Digital Strategy Services & Consultancy | Local Foundary',
    seoDescription: 'Digital strategy for growing businesses: audits, positioning, customer journey mapping and a prioritised roadmap for UK and international clients.',
  },
  {
    slug: 'website-design',
    name: 'Website design & development',
    eyebrow: 'Design & development',
    title: 'Website design built around your business — not a template.',
    intro: 'A premium website should clarify your offer, build trust quickly and make the next step easy. Every experience is designed around your company, customer and commercial objective.',
    deliverables: ['Discovery and UX strategy', 'Content structure', 'Responsive interface design', 'Front-end development', 'Forms and integrations', 'Technical SEO', 'Accessibility and launch QA'],
    relatedProject: 'pat-barrett',
    seoTitle: 'Bespoke Website Design & Development UK | Local Foundary',
    seoDescription: 'Bespoke website design and development from a UK-based agency, creating responsive journeys for businesses in the UK and internationally.',
  },
  {
    slug: 'ecommerce',
    name: 'E-commerce website design',
    eyebrow: 'E-commerce',
    title: 'E-commerce websites designed to make buying feel easy.',
    intro: 'We create e-commerce experiences with clear navigation, strong product presentation and a low-friction journey from discovery to checkout.',
    deliverables: ['Store and catalogue strategy', 'Product information structure', 'Responsive shop design', 'Product and collection templates', 'Checkout and payment integration', 'Email and analytics setup', 'Launch and trading QA'],
    relatedProject: 'pat-barrett',
    seoTitle: 'E-commerce Website Design & Development UK | Local Foundary',
    seoDescription: 'Conversion-focused e-commerce website design with clear product discovery, strong presentation, payments and responsive buying journeys.',
  },
  {
    slug: 'branding',
    name: 'Brand identity design',
    eyebrow: 'Positioning & identity',
    title: 'A brand identity people understand — and remember.',
    intro: 'We shape the position, message and visual system that help a good business feel clear, consistent and established wherever customers meet it.',
    deliverables: ['Brand discovery', 'Positioning', 'Core messaging', 'Typographic direction', 'Colour system', 'Wordmark direction', 'Practical brand guidelines'],
    relatedProject: 'iffy-khan',
    seoTitle: 'Brand Identity Design & Positioning | Local Foundary',
    seoDescription: 'Brand positioning, messaging and visual identity systems for growing businesses that need to communicate with greater clarity and confidence.',
  },
  {
    slug: 'local-seo',
    name: 'SEO & search visibility',
    eyebrow: 'Search visibility',
    title: 'SEO that builds visibility where customers are already looking.',
    intro: 'We connect technical SEO, useful content and the right local or national search structure so customers can discover and understand what you offer.',
    deliverables: ['Search and competitor review', 'Technical SEO foundations', 'Content and service structure', 'On-page optimisation', 'Internal linking', 'Appropriate structured data', 'Measurement plan'],
    relatedProject: 'ste-hamilton-fitness',
    seoTitle: 'Local SEO & Search Visibility Services | Local Foundary',
    seoDescription: 'Local and national SEO services from a UK-based agency: technical improvements, content structure and honest measurement without ranking guarantees.',
  },
  {
    slug: 'google-business-profile',
    name: 'Google Business Profile optimisation',
    eyebrow: 'Google presence',
    title: 'Make your Google Business Profile earn the click.',
    intro: 'We organise and improve the information customers see in Google — from categories and services to imagery, review journeys and website alignment.',
    deliverables: ['Profile audit', 'Category and service setup', 'Business information review', 'Image guidance', 'Review journey', 'Website alignment', 'Ongoing recommendations'],
    relatedProject: 'ste-hamilton-fitness',
    seoTitle: 'Google Business Profile Optimisation | Local Foundary',
    seoDescription: 'Google Business Profile setup and optimisation for companies that want a clearer, stronger presence across local search and Maps.',
  },
  {
    slug: 'landing-pages-lead-generation',
    name: 'Landing pages & lead generation',
    eyebrow: 'Landing pages & conversion',
    title: 'Landing pages and lead generation designed around qualified action.',
    intro: 'We create focused landing pages, forms, booking journeys and lead-generation systems that make the offer clear and remove friction from the next step.',
    deliverables: ['Campaign and audience review', 'Landing-page strategy', 'Conversion copy', 'Responsive page design', 'Forms and qualification', 'Booking or CRM integrations', 'Tracking plan'],
    relatedProject: 'iffy-khan',
    seoTitle: 'Landing Page Design & Lead Generation | Local Foundary',
    seoDescription: 'Focused landing pages, forms, booking integrations and lead-generation journeys designed around clear offers and qualified actions.',
  },
  {
    slug: 'copy-content',
    name: 'Website copywriting & content',
    eyebrow: 'Copy & content',
    title: 'Website copywriting that makes your value easy to understand.',
    intro: 'We shape website copy and content structure around what customers need to know, believe and do — without empty claims or generic agency language.',
    deliverables: ['Messaging framework', 'Website copy planning', 'Page-by-page copywriting', 'Service and product content', 'Calls to action', 'Search-informed structure', 'Editing and tone consistency'],
    relatedProject: 'pat-barrett',
    seoTitle: 'Website Copywriting & Content Strategy | Local Foundary',
    seoDescription: 'Website copywriting, messaging and content strategy that communicate value clearly, build trust and guide customers towards action.',
  },
  {
    slug: 'hosting-support',
    name: 'Website hosting & maintenance',
    eyebrow: 'Hosting & ongoing support',
    title: 'Reliable website hosting, maintenance and support.',
    intro: 'We provide hosting, maintenance, technical checks and practical updates through a scope that keeps responsibilities and ongoing costs clear.',
    deliverables: ['Standard hosting setup', 'SSL configuration', 'Backup and update responsibilities', 'Performance checks', 'Content-update options', 'Technical support scope', 'Exit and migration plan'],
    relatedProject: 'ste-hamilton-fitness',
    seoTitle: 'Website Hosting, Maintenance & Care Plans | Local Foundary',
    seoDescription: 'Website hosting, maintenance and support, scoped in writing. Two years of hosting with every package, then a £29 monthly care plan or £59 annual renewal.',
  },
  {
    slug: 'digital-growth',
    name: 'Digital growth',
    eyebrow: 'Complete online presence',
    title: 'A digital growth partner for your whole online presence.',
    intro: 'Strategy, brand, website, search, content and conversion work harder when they are designed as one system instead of bought as disconnected services.',
    deliverables: ['Online presence audit', 'Priorities and dependencies', 'Website and content roadmap', 'Search visibility', 'Conversion journeys', 'Measurement plan', 'Agreed review points'],
    relatedProject: 'iffy-khan',
    seoTitle: 'Digital Growth & Online Presence Services | Local Foundary',
    seoDescription: 'A connected digital growth service bringing strategy, brand, websites, search visibility, content and conversion systems together.',
  },
];

export const industryPageData = {
  'websites-for-plumbers': {
    title: 'Plumbers’ websites that work at call-out speed.',
    eyebrow: 'Plumbers & heating engineers',
    intro: 'Mobile-first websites that make services, areas, trust signals and the route to call immediately clear — without making every page sound the same.',
    needs: ['Emergency and planned-work journeys', 'Service and area pages', 'Accreditation and review placement', 'Click-to-call and quote forms', 'Local SEO and service-area structure'],
    seoTitle: 'Websites for Plumbers & Heating Engineers | Local Foundary',
    seoDescription: 'Professional, mobile-first websites for plumbers and heating engineers, with clear call journeys, local SEO and trust signals.',
    matterTitle: 'What a useful plumbing website needs.',
    matterCopy: 'A customer with a leak and a customer planning a new bathroom need different information. The structure should make both routes immediate.',
    contextTitle: 'Built for plumbing decisions.<br>Connected to wider digital expertise.',
    contextCopy: 'Service and area pages, accreditation, mobile contact and local search need to reinforce one another. We tailor that system to your services and working area without making unsupported ranking promises.',
    ctaTitle: 'Ready for a plumbing website customers can act on?',
  },
  'websites-for-electricians': {
    title: 'Electricians’ websites that make electrical expertise easy to trust.',
    eyebrow: 'Electricians',
    intro: 'A clear digital presence for domestic, commercial and specialist electrical work — designed to help customers understand capability and request the right quote.',
    needs: ['Domestic and commercial service paths', 'Accreditation placement', 'Project and proof content', 'Quote qualification', 'Local SEO and service-area structure'],
    seoTitle: 'Websites for Electricians | Local Foundary',
    seoDescription: 'Professional websites for electricians and electrical contractors, built around trust, services, projects and quote enquiries.',
    matterTitle: 'What helps an electrical contractor earn trust online.',
    matterCopy: 'Customers need to see the work you undertake, the credentials behind it and the right route for a domestic, commercial or specialist enquiry.',
    contextTitle: 'Structured around electrical services.<br>Designed for the right enquiry.',
    contextCopy: 'Accreditations, project evidence, service pages and quote questions are organised around how customers compare electrical contractors. Domestic, commercial and specialist work can then lead into different, better-qualified enquiry routes. Search outcomes still depend on competition, content and ongoing activity.',
    ctaTitle: 'Ready to make your electrical expertise easier to choose?',
  },
  'websites-for-builders': {
    title: 'Builders’ websites that turn completed projects into serious enquiries.',
    eyebrow: 'Builders & construction',
    intro: 'Project-led websites that give extensions, renovations and new-build work the space they deserve while helping customers understand scope and fit.',
    needs: ['Editorial project galleries', 'Service and project-type pages', 'Before-and-after presentation', 'Enquiry qualification', 'Local SEO and service-area structure'],
    seoTitle: 'Websites for Builders & Construction | Local Foundary',
    seoDescription: 'Project-led websites for builders and construction companies, with galleries, service content and qualified enquiry journeys.',
    matterTitle: 'What turns project interest into a serious building enquiry.',
    matterCopy: 'The website should show the standard of completed work, clarify the projects you want and gather enough detail to make the first response useful.',
    contextTitle: 'Your completed work is the proof.<br>The website gives it structure.',
    contextCopy: 'Editorial galleries, service detail and project qualification help potential clients understand fit before they enquire. Visibility and enquiry volume vary by market and ongoing activity.',
    ctaTitle: 'Ready to turn completed work into better project enquiries?',
  },
  'websites-for-service-businesses': {
    title: 'Websites for service businesses built to win enquiries.',
    eyebrow: 'Local service businesses',
    intro: 'For consultants, coaches and appointment-led specialists, the website has to make expertise, personality and the next step tangible.',
    needs: ['Clear offer and positioning', 'Service comparison', 'Enquiry integration', 'Proof and personality', 'Local SEO and service-area structure'],
    seoTitle: 'Websites for Local Service Businesses | Local Foundary',
    seoDescription: 'Professional websites for consultants, coaches and service-led businesses, built around clear positioning, trust and qualified enquiries.',
    matterTitle: 'What makes an expert service easier to choose.',
    matterCopy: 'When the value is intangible, clear positioning, packaged services, relevant proof and a confident enquiry journey do the work a physical product cannot.',
    contextTitle: 'Built around expertise and trust.<br>Not a generic service template.',
    contextCopy: 'The structure adapts to your offer, customer questions and preferred next step, with search and conversion foundations connected to the same message.',
    ctaTitle: 'Ready for a service website that earns the enquiry?',
  },
};
